version: "3.8"

services:
  database_ignite:
    image: postgres
    container_name: queries_challenge
    restart: always
    environment:
      POSTGRES_DB:  queries_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
      
volumes:
    pgdata:
      driver: local